
from pynput.keyboard import Key, Controller as KeyboardController
from pynput.mouse import Button, Controller as MouseController

import time


mouse = MouseController()

# In the future would have to code in the path breaks

time.sleep(1)

#========================================================
# Level 1
#=========================================================

time.sleep(.03)
#---------------
mouse.position = (1557, 661)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1487, 663)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1484, 591)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1482, 512)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1471, 356)
mouse.release(Button.left)

time.sleep(.05)

mouse.position = (1624, 360)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1562, 365)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1555, 441)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1558, 590)
mouse.release(Button.left)

time.sleep(.05)
mouse.position = (1620, 674)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1637, 593)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1628, 447)
mouse.release(Button.left)

time.sleep(.05)
mouse.position = (1708, 593)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1715, 528)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1708, 442)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1785, 367)
mouse.release(Button.left)

time.sleep(.05)
mouse.position = (1779, 443)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1786, 511)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1783, 594)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1723, 661)
mouse.release(Button.left)


time.sleep(2)
mouse.position = (1634, 539)
mouse.press(Button.left)
mouse.release(Button.left)

time.sleep(1)
#========================================================
# Level 2
#=========================================================

mouse.position = (1488, 368)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1562, 368)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1638, 368)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1700, 368)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1782, 366)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1788, 447)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1782, 597)
mouse.release(Button.left)

time.sleep(.05)
mouse.position = (1782, 674)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1720, 670)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1718, 585)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1711, 517)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1711, 437)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1633, 437)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1552, 437)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1484, 437)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1475, 589)
mouse.release(Button.left)

time.sleep(.05)
mouse.position = (1576, 596)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1620, 520)
mouse.release(Button.left)

time.sleep(.05)
mouse.position = (1632, 597)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1634, 665)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1506, 663)
mouse.release(Button.left)


time.sleep(2)
mouse.position = (1634, 539)
mouse.press(Button.left)
mouse.release(Button.left)

time.sleep(1)
#========================================================
# Level 3
#=========================================================

mouse.position = (1555, 378)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1479, 375)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1481, 444)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1481, 596)
mouse.release(Button.left)

time.sleep(.05)
mouse.position = (1483, 672)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1556, 671)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1554, 596)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1551, 526)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1554, 442)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1632, 399)
mouse.release(Button.left)

time.sleep(.05)
mouse.position = (1712, 379)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1781, 362)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1781, 435)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1779, 528)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1792, 605)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1723, 666)
mouse.release(Button.left)

time.sleep(.05)
mouse.position = (1644, 669)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1710, 585)
mouse.release(Button.left)

time.sleep(.05)
mouse.position = (1629, 511)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1712, 444)
mouse.release(Button.left)


time.sleep(2)
mouse.position = (1634, 539)
mouse.press(Button.left)
mouse.release(Button.left)

time.sleep(1)
#========================================================
# Level 4
#=========================================================

mouse.position = (1492, 447)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1491, 362)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1553, 370)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1699, 371)
mouse.release(Button.left)

time.sleep(.05)
mouse.position = (1782, 375)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1776, 452)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1715, 449)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1642, 437)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1565, 433)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1563, 520)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1490, 510)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1488, 678)
mouse.release(Button.left)

time.sleep(.05)
mouse.position = (1560, 671)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1565, 598)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1701, 596)
mouse.release(Button.left)

time.sleep(.05)
mouse.position = (1630, 509)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1706, 515)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1776, 520)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1779, 597)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1778, 669)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1640, 669)
mouse.release(Button.left)


time.sleep(2)
mouse.position = (1634, 539)
mouse.press(Button.left)
mouse.release(Button.left)

time.sleep(1)
#========================================================
# Level 5
#=========================================================

mouse.position = (1704, 371)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1624, 371)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1560, 371)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1480, 367)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1485, 440)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1483, 514)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1485, 589)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1487, 667)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1634, 675)
mouse.release(Button.left)

time.sleep(.05)
mouse.position = (1788, 666)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1715, 671)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1716, 600)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1638, 591)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1551, 589)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1557, 451)
mouse.release(Button.left)

time.sleep(.05)
mouse.position = (1629, 450)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1637, 517)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1712, 509)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1784, 592)
mouse.release(Button.left)

time.sleep(.05)
mouse.position = (1707, 444)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1789, 382)
mouse.release(Button.left)


time.sleep(2)
mouse.position = (1634, 539)