
from pynput.keyboard import Key, Controller as KeyboardController
from pynput.mouse import Button, Controller as MouseController

import time


mouse = MouseController()

# In the future would have to code in the path breaks

time.sleep(1)

#========================================================
# Level 1
#=========================================================

mouse.position = (1659, 540)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1614, 501)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1658, 495)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1702, 495)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1702, 543)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1662, 590)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1655, 448)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1612, 448)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1566, 447)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1566, 488)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1565, 536)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1559, 591)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1611, 592)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1612, 638)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1658, 638)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1711, 631)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1749, 637)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1750, 586)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1752, 543)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1749, 492)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1747, 400)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1791, 403)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1793, 355)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1746, 355)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1708, 355)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1702, 453)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1800, 453)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1794, 497)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1799, 542)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1799, 594)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1796, 639)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1795, 679)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1747, 681)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1701, 681)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1649, 679)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1608, 681)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1554, 683)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1557, 636)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1518, 636)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1517, 592)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1518, 542)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1523, 496)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1519, 445)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1519, 404)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1565, 404)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1659, 400)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1519, 680)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1467, 680)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1469, 631)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1469, 581)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1470, 539)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1470, 487)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1462, 437)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1469, 397)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1471, 355)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1514, 353)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1567, 353)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1659, 355)
mouse.release(Button.left)

time.sleep(1)
mouse.position = (1634, 539)
mouse.press(Button.left)
mouse.release(Button.left)

time.sleep(1)
#========================================================
# Level 2
#=========================================================
mouse.position = (1469, 680)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1466, 639)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1520, 635)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1514, 584)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1568, 585)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1617, 588)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1659, 584)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1654, 544)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1658, 497)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1653, 449)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1614, 448)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1567, 452)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1509, 449)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1471, 446)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1470, 355)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1517, 356)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1525, 403)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1570, 402)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1606, 400)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1663, 400)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1702, 403)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1703, 441)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1706, 489)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1705, 592)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1609, 495)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1612, 545)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1567, 542)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1518, 541)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1461, 584)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1471, 494)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1559, 498)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1565, 358)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1613, 358)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1652, 358)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1697, 358)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1756, 351)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1793, 351)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1799, 402)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1801, 446)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1802, 496)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1800, 540)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1794, 589)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1796, 634)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1798, 683)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1751, 682)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1709, 683)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1615, 685)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1520, 683)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1559, 682)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1556, 635)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1607, 634)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1657, 632)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1701, 633)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1752, 632)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1754, 586)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1751, 546)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1751, 500)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1748, 401)
mouse.release(Button.left)

time.sleep(1)
mouse.position = (1634, 539)
mouse.press(Button.left)
mouse.release(Button.left)

time.sleep(1)
#========================================================
# Level 3
#=========================================================
mouse.position = (1515, 353)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1470, 353)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1469, 403)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1468, 443)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1466, 492)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1475, 544)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1517, 545)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1605, 543)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1610, 590)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1556, 586)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1515, 586)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1471, 587)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1469, 639)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1469, 682)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1520, 681)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1565, 681)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1613, 680)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1656, 682)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1747, 682)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1796, 682)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1795, 636)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1744, 631)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1695, 633)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1702, 580)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1703, 545)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1700, 499)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1658, 498)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1609, 492)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1567, 496)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1517, 495)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1512, 450)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1513, 400)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1563, 401)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1567, 358)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1612, 358)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1654, 358)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1702, 355)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1751, 352)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1794, 350)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1794, 402)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1795, 444)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1799, 545)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1795, 589)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1761, 593)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1754, 540)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1754, 492)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1749, 453)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1704, 451)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1656, 447)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1568, 447)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1752, 404)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1707, 403)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1617, 403)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1655, 542)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1654, 581)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1655, 640)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1615, 643)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1521, 633)
mouse.release(Button.left)

time.sleep(1)
mouse.position = (1634, 539)
mouse.press(Button.left)
mouse.release(Button.left)

time.sleep(1)
#========================================================
# Level 4
#=========================================================
mouse.position = (1803, 631)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1797, 678)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1754, 680)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1700, 685)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1657, 685)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1616, 684)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1573, 681)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1515, 682)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1475, 683)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1462, 635)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1467, 579)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1474, 543)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1477, 493)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1477, 447)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1477, 357)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1796, 400)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1799, 356)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1751, 357)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1701, 356)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1656, 356)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1608, 356)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1560, 356)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1519, 356)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1517, 402)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1515, 501)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1748, 402)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1709, 398)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1655, 394)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1608, 395)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1562, 401)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1567, 446)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1566, 492)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1609, 493)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1667, 494)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1758, 498)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1797, 496)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1795, 446)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1748, 451)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1704, 453)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1605, 452)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1562, 631)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1522, 633)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1521, 594)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1517, 543)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1559, 541)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1655, 539)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1563, 591)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1608, 591)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1653, 591)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1705, 590)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1706, 540)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1796, 540)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1794, 588)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1750, 592)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1752, 636)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1695, 640)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1605, 637)
mouse.release(Button.left)


time.sleep(1)
mouse.position = (1634, 539)
mouse.press(Button.left)
mouse.release(Button.left)

time.sleep(1)
#========================================================
# Level 5
#=========================================================
mouse.position = (1799, 357)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1750, 354)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1706, 355)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1652, 355)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1603, 354)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1558, 351)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1511, 354)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1466, 360)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1466, 401)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1467, 446)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1469, 493)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1519, 494)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1607, 492)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1803, 541)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1803, 503)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1753, 499)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1750, 445)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1709, 447)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1654, 446)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1602, 446)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1565, 446)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1519, 416)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1800, 451)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1792, 403)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1749, 399)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1707, 403)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1663, 401)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1565, 399)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1703, 499)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1661, 495)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1655, 539)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1610, 548)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1562, 541)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1513, 542)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1478, 542)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1474, 595)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1475, 682)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1705, 543)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1699, 585)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1654, 587)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1606, 590)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1563, 590)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1517, 589)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1516, 631)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1513, 685)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1560, 682)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1611, 682)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1663, 682)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1705, 682)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1744, 682)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1797, 683)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1798, 591)
mouse.release(Button.left)
time.sleep(.02)
#---------------
mouse.position = (1750, 545)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1751, 590)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1754, 630)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1698, 636)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1649, 638)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.05)
mouse.position = (1562, 634)
mouse.release(Button.left)


time.sleep(1)
mouse.position = (1634, 539)