
from pynput.keyboard import Key, Controller as KeyboardController
from pynput.mouse import Button, Controller as MouseController

import time


mouse = MouseController()

# In the future would have to code in the path breaks

time.sleep(1)

#========================================================
# Level 1
#=========================================================

mouse.position = (1474, 361)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1477, 426)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1487, 494)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1481, 613)
mouse.release(Button.left)

time.sleep(.01)



mouse.position = (1481, 676)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1539, 671)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1539, 609)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1532, 549)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1544, 484)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1546, 367)
mouse.release(Button.left)

time.sleep(.01)


mouse.position = (1603, 366)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1604, 488)
mouse.release(Button.left)



time.sleep(.01)


mouse.position = (1609, 545)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1665, 540)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1664, 483)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1662, 415)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1728, 363)
mouse.release(Button.left)


time.sleep(.01)


mouse.position = (1726, 425)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1733, 485)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1727, 553)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1727, 621)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1610, 613)
mouse.release(Button.left)


time.sleep(.01)


mouse.position = (1598, 675)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1664, 675)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1730, 674)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1795, 673)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1791, 599)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1797, 540)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1797, 490)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1796, 370)
mouse.release(Button.left)



time.sleep(1)
mouse.position = (1634, 539)
mouse.press(Button.left)
mouse.release(Button.left)

time.sleep(1)
#========================================================
# Level 2
#=========================================================

mouse.position = (1540, 361)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1480, 363)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1479, 425)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1480, 489)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1485, 551)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1482, 606)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1477, 670)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1550, 670)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1605, 674)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1659, 674)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1732, 674)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1794, 611)
mouse.release(Button.left)

time.sleep(.01)


mouse.position = (1723, 613)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1662, 545)
mouse.release(Button.left)


time.sleep(.01)



mouse.position = (1604, 612)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1606, 491)
mouse.release(Button.left)


time.sleep(.01)



mouse.position = (1540, 608)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1541, 542)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1541, 478)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1545, 420)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1601, 419)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1667, 490)
mouse.release(Button.left)


time.sleep(.01)



mouse.position = (1609, 364)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1660, 364)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1724, 363)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1723, 420)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1728, 485)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1788, 551)
mouse.release(Button.left)


time.sleep(.01)


mouse.position = (1785, 492)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1794, 364)
mouse.release(Button.left)



time.sleep(1)
mouse.position = (1634, 539)
mouse.press(Button.left)
mouse.release(Button.left)

time.sleep(1)
#========================================================
# Level 3
#=========================================================
mouse.position = (1599, 610)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1552, 612)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1556, 549)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1545, 430)
mouse.release(Button.left)



time.sleep(.01)



mouse.position = (1608, 674)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1529, 673)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1476, 670)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1479, 611)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1482, 549)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1479, 486)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1472, 424)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1479, 371)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1538, 364)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1597, 364)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1605, 425)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1606, 484)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1606, 552)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1665, 614)
mouse.release(Button.left)

time.sleep(.01)

mouse.position = (1728, 615)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1734, 544)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1727, 422)
mouse.release(Button.left)

time.sleep(.01)

mouse.position = (1671, 674)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1737, 674)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1784, 677)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1789, 617)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1787, 550)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1785, 486)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1786, 420)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1788, 361)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1730, 368)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1670, 362)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1662, 490)
mouse.release(Button.left)


time.sleep(1)
mouse.position = (1634, 539)
mouse.press(Button.left)
mouse.release(Button.left)

time.sleep(1)
#========================================================
# Level 4
#=========================================================

mouse.position = (1477, 360)

mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1549, 360)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1601, 362)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1662, 362)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1722, 362)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1786, 360)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1786, 421)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1790, 488)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1795, 550)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1793, 612)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1783, 671)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1729, 670)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1669, 668)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1606, 668)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1541, 670)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1479, 610)
mouse.release(Button.left)


time.sleep(.01)


mouse.position = (1541, 609)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1600, 552)
mouse.release(Button.left)


time.sleep(.01)


mouse.position = (1662, 549)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1666, 481)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1604, 487)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1541, 546)
mouse.release(Button.left)


time.sleep(.01)


mouse.position = (1476, 549)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1481, 486)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1483, 427)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1536, 422)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1603, 422)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1666, 422)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1723, 420)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1720, 480)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1729, 548)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1669, 610)
mouse.release(Button.left)


time.sleep(1)
mouse.position = (1634, 539)
mouse.press(Button.left)
mouse.release(Button.left)

time.sleep(1)
#========================================================
# Level 5
#=========================================================

mouse.position = (1476, 365)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1554, 359)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1606, 361)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1665, 358)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1730, 358)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1790, 359)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1786, 420)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1793, 486)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1793, 546)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1793, 602)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1729, 677)
mouse.release(Button.left)

time.sleep(.01)


mouse.position = (1724, 609)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1663, 612)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1667, 673)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1601, 676)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1538, 676)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1479, 671)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1473, 611)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1476, 552)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1544, 545)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1544, 490)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1670, 486)
mouse.release(Button.left)

time.sleep(.01)


mouse.position = (1730, 489)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1729, 433)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1668, 429)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1606, 429)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1540, 428)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1483, 488)
mouse.release(Button.left)

time.sleep(.01)


mouse.position = (1542, 612)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1604, 611)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1598, 554)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1726, 550)
mouse.release(Button.left)


time.sleep(1)
mouse.position = (1634, 539)