
from pynput.keyboard import Key, Controller as KeyboardController
from pynput.mouse import Button, Controller as MouseController

import time


mouse = MouseController()

# In the future would have to code in the path breaks

time.sleep(1)

#========================================================
# Level 1
#=========================================================

mouse.position = (1795, 359)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1740, 356)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1685, 356)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1632, 356)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1581, 355)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1526, 352)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1473, 352)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1479, 413)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1476, 469)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1474, 514)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1473, 568)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1473, 623)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1471, 680)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1523, 681)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1589, 682)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1632, 682)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1744, 682)
mouse.release(Button.left)

time.sleep(.01)
#---------------

mouse.position = (1792, 678)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1791, 624)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1792, 567)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1798, 512)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1693, 522)
mouse.release(Button.left)

time.sleep(.01)
#---------------

mouse.position = (1622, 547)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1579, 575)
mouse.release(Button.left)

time.sleep(.01)
#---------------


mouse.position = (1742, 624)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1677, 574)
mouse.release(Button.left)

time.sleep(.01)
#---------------

mouse.position = (1684, 624)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1635, 624)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1574, 625)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1533, 625)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1527, 572)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1528, 518)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1579, 512)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1582, 470)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1630, 464)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1691, 461)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1742, 459)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1789, 410)
mouse.release(Button.left)

time.sleep(.01)
#---------------

mouse.position = (1742, 415)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1686, 412)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1631, 410)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1573, 406)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1525, 469)
mouse.release(Button.left)


time.sleep(1)
mouse.position = (1634, 539)
mouse.press(Button.left)
mouse.release(Button.left)

time.sleep(1)
#========================================================
# Level 2
#=========================================================

mouse.position = (1525, 357)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1472, 356)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1468, 417)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1468, 463)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1472, 515)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1476, 571)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1472, 630)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1469, 679)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1579, 678)
mouse.release(Button.left)

time.sleep(.01)
#---------------

mouse.position = (1582, 633)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1532, 627)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1532, 568)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1532, 515)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1531, 459)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1578, 410)
mouse.release(Button.left)

time.sleep(.01)
#---------------
mouse.position = (1581, 356)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1635, 351)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1687, 352)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1747, 357)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1795, 357)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1793, 411)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1794, 464)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1791, 516)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1795, 570)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1794, 625)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1793, 675)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1741, 676)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1636, 678)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1741, 574)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1736, 628)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1691, 628)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1635, 622)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1634, 577)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1582, 521)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1630, 521)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1689, 574)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1737, 519)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1738, 463)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1684, 461)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1590, 467)
mouse.release(Button.left)
time.sleep(.01)
#---------------

mouse.position = (1634, 412)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1739, 413)
mouse.release(Button.left)


time.sleep(1)
mouse.position = (1634, 539)
mouse.press(Button.left)
mouse.release(Button.left)

time.sleep(1)
#========================================================
# Level 3
#=========================================================

mouse.position = (1798, 408)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1789, 358)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1733, 359)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1686, 358)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1637, 355)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1578, 355)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1474, 359)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1800, 467)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1746, 466)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1741, 416)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1680, 410)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1633, 412)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1579, 415)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1473, 416)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1472, 466)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1578, 463)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1637, 464)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1630, 511)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1632, 570)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1747, 575)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1690, 466)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1688, 517)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1795, 517)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1797, 573)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1796, 628)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1742, 628)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1695, 628)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1629, 628)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1584, 626)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1577, 521)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1471, 520)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1471, 520)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1529, 514)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1530, 628)
mouse.release(Button.left)
time.sleep(.01)
#---------------

mouse.position = (1479, 575)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1471, 623)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1465, 677)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1525, 682)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1576, 679)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1642, 677)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1682, 679)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1797, 682)
mouse.release(Button.left)


time.sleep(1)
mouse.position = (1634, 539)
mouse.press(Button.left)
mouse.release(Button.left)

time.sleep(1)
#========================================================
# Level 4
#=========================================================

mouse.position = (1471, 412)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1468, 357)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1526, 360)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1582, 360)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1631, 358)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1694, 358)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1742, 358)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1793, 355)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1791, 418)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1802, 452)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1799, 506)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1798, 559)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1800, 623)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1797, 676)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1739, 677)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1685, 676)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1638, 676)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1583, 677)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1472, 680)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1471, 624)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1466, 569)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1473, 510)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1471, 463)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1529, 465)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1522, 403)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1586, 413)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1632, 415)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1694, 412)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1737, 412)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1741, 460)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1738, 516)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1739, 623)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1582, 575)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1583, 625)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1682, 619)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1530, 623)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1528, 574)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1533, 517)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1581, 519)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1630, 520)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1681, 573)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1683, 517)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1682, 470)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1584, 470)
mouse.release(Button.left)


time.sleep(1)
mouse.position = (1634, 539)
mouse.press(Button.left)
mouse.release(Button.left)

time.sleep(1)
#========================================================
# Level 5
#=========================================================

mouse.position = (1528, 684)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1474, 679)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1473, 624)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1474, 576)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1474, 515)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1475, 468)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1475, 371)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1529, 360)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1533, 411)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1582, 411)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1634, 411)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1689, 413)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1692, 524)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1688, 575)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1741, 573)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1743, 517)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1745, 416)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1582, 359)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1631, 359)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1694, 358)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1751, 357)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1800, 357)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1799, 426)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1795, 465)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1796, 523)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1797, 576)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1797, 576)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1796, 625)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1742, 629)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1685, 626)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1628, 626)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1633, 570)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1626, 456)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1529, 463)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1579, 462)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1582, 575)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1531, 524)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1528, 562)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1529, 619)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1583, 627)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1586, 682)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1633, 676)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1690, 675)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1796, 679)
mouse.release(Button.left)


time.sleep(1)
mouse.position = (1634, 539)

