
from pynput.keyboard import Key, Controller as KeyboardController
from pynput.mouse import Button, Controller as MouseController

import time


mouse = MouseController()

# In the future would have to code in the path breaks

time.sleep(1)

#========================================================
# Level 1
#=========================================================

mouse.position = (1465, 565)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1467, 520)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1470, 477)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1468, 428)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1469, 391)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1472, 355)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1514, 355)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1549, 354)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1588, 354)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1630, 351)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1675, 349)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1716, 349)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1753, 350)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1801, 354)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1799, 393)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1799, 434)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1804, 481)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1804, 516)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1768, 520)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1722, 520)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1719, 556)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1716, 603)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1680, 603)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1636, 602)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1556, 601)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1507, 599)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1467, 601)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1466, 644)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1473, 685)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1512, 681)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1555, 681)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1587, 681)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1633, 680)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1682, 684)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1718, 684)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1758, 685)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1801, 685)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1804, 639)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1798, 558)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1511, 639)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1544, 640)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1592, 643)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1642, 642)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1686, 641)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1720, 639)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1759, 639)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1760, 558)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1756, 473)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1714, 473)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1669, 478)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1673, 517)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1675, 555)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1627, 555)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1594, 558)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1510, 558)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1506, 518)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1592, 520)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1636, 524)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1633, 476)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1591, 475)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1543, 475)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1511, 475)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1514, 395)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1549, 394)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1591, 438)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1758, 434)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1764, 394)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1719, 394)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1675, 392)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1591, 392)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1639, 435)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1715, 437)
mouse.release(Button.left)


time.sleep(1)
mouse.position = (1634, 539)
mouse.press(Button.left)
mouse.release(Button.left)

time.sleep(1)
#========================================================
# Level 2
#=========================================================
mouse.position = (1759, 354)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1797, 351)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1798, 397)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1804, 436)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1803, 483)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1802, 522)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1804, 561)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1802, 599)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1803, 643)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1803, 683)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1751, 687)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1709, 683)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1671, 685)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1628, 681)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1631, 641)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1635, 603)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1669, 603)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1716, 603)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1715, 557)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1717, 517)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1716, 470)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1715, 435)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1671, 436)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1674, 395)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1634, 395)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1596, 396)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1548, 396)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1507, 395)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1473, 395)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1470, 480)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1466, 353)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1507, 353)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1547, 351)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1591, 355)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1633, 353)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1675, 352)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1715, 352)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1716, 395)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1758, 393)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1761, 478)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1754, 518)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1755, 560)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1761, 605)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1757, 644)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1674, 642)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1678, 558)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1673, 471)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1630, 558)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1637, 521)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1634, 479)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1634, 435)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1589, 438)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1549, 438)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1514, 439)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1508, 478)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1510, 520)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1477, 518)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1463, 564)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1462, 599)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1466, 645)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1470, 682)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1555, 687)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1514, 645)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1509, 561)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1592, 481)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1554, 478)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1551, 518)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1553, 560)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1557, 652)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1591, 683)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1596, 640)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1594, 602)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1596, 521)
mouse.release(Button.left)


time.sleep(1)
mouse.position = (1634, 539)
mouse.press(Button.left)
mouse.release(Button.left)

time.sleep(1)
#========================================================
# Level 3
#=========================================================

mouse.position = (1758, 356)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1799, 356)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1802, 391)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1801, 436)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1811, 518)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1803, 601)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1802, 646)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1802, 682)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1759, 687)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1714, 686)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1668, 686)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1631, 686)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1594, 685)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1550, 685)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1502, 685)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1472, 685)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1470, 646)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1465, 596)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1469, 558)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1473, 474)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1508, 396)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1516, 433)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1557, 431)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1593, 435)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1630, 437)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1635, 528)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1469, 435)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1469, 389)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1467, 348)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1510, 346)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1548, 346)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1594, 350)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1634, 350)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1676, 350)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1714, 350)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1718, 397)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1758, 393)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1759, 436)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1764, 477)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1759, 515)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1718, 516)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1715, 560)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1712, 599)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1673, 601)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1635, 601)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1584, 601)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1551, 601)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1550, 522)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1804, 562)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1766, 561)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1760, 613)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1763, 638)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1725, 646)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1676, 642)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1632, 641)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1592, 641)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1545, 641)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1499, 642)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1507, 599)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1507, 557)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1511, 524)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1510, 481)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1540, 481)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1588, 481)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1593, 519)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1639, 562)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1677, 560)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1675, 475)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1718, 478)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1719, 435)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1679, 437)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1674, 392)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1631, 394)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1559, 394)
mouse.release(Button.left)


time.sleep(1)
mouse.position = (1634, 539)
mouse.press(Button.left)
mouse.release(Button.left)

time.sleep(1)
#========================================================
# Level 4
#=========================================================

mouse.position = (1803, 642)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1799, 558)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1801, 524)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1757, 519)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1759, 559)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1761, 607)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1753, 641)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1791, 685)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1760, 475)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1722, 476)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1719, 513)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1723, 559)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1713, 596)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1713, 648)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1713, 680)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1673, 681)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1635, 687)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1595, 684)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1549, 685)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1510, 684)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1473, 684)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1463, 637)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1463, 598)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1462, 557)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1469, 511)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1466, 472)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1471, 434)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1470, 353)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1513, 351)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1513, 386)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1509, 435)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1509, 474)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1510, 513)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1505, 556)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1506, 592)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1507, 636)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1547, 638)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1585, 644)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1630, 645)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1672, 645)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1676, 597)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1672, 556)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1635, 558)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1594, 556)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1592, 517)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1588, 475)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1592, 388)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1635, 600)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1599, 598)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1553, 599)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1556, 562)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1552, 517)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1550, 471)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1548, 434)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1553, 391)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1555, 354)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1589, 352)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1635, 350)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1675, 350)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1722, 350)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1802, 349)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1795, 395)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1767, 395)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1714, 394)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1673, 394)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1630, 395)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1630, 476)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1798, 477)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1802, 433)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1762, 435)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1711, 435)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1684, 435)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1680, 478)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1641, 517)
mouse.release(Button.left)




time.sleep(1)
mouse.position = (1634, 539)
mouse.press(Button.left)
mouse.release(Button.left)

time.sleep(1)
#========================================================
# Level 5
#=========================================================
mouse.position = (1594, 479)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1550, 479)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1550, 437)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1554, 393)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1550, 352)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1472, 356)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1466, 397)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1511, 393)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1516, 437)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1505, 482)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1513, 517)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1511, 561)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1511, 645)
mouse.release(Button.left)

time.sleep(.01)
#---------------
mouse.position = (1801, 603)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1796, 643)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1800, 681)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1763, 688)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1712, 688)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1672, 683)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1639, 686)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1591, 686)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1547, 683)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1504, 683)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1470, 683)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1462, 643)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1465, 600)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1461, 554)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1461, 512)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1472, 440)
mouse.release(Button.left)

time.sleep(.01)
#---------------
mouse.position = (1758, 602)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1761, 560)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1794, 560)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1799, 513)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1805, 471)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1801, 426)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1799, 395)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1798, 357)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1762, 356)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1715, 355)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1676, 355)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1637, 357)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1598, 354)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1586, 390)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1592, 436)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1636, 436)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1638, 480)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1633, 521)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1603, 522)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1559, 522)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1549, 560)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1553, 645)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1591, 558)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1590, 601)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1592, 643)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1637, 643)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1676, 641)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1758, 640)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1630, 601)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1635, 560)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1678, 560)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1676, 517)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1676, 436)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1675, 599)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1717, 602)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1723, 560)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1721, 519)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1763, 522)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1759, 471)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1764, 392)
mouse.release(Button.left)
time.sleep(.01)
#---------------
mouse.position = (1718, 477)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1719, 437)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1716, 389)
mouse.release(Button.left)
mouse.press(Button.left)
time.sleep(.01)
mouse.position = (1638, 393)
mouse.release(Button.left)



time.sleep(1)
mouse.position = (1634, 539)